### ISSUE TITLE
Add a name to Notification

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/SPASE-General#3]
Hello, please add Andriy Koval andriy.koval-1@nasa.gov to these lists: 

--SPASE validators: James, Lee, Scott 

--Github pushers: (SPASE resource registration): James, Lee, Scott

--Registration alert receivers: Jen, Lee, Chuck, James, Catherine, Tressa)
Thank you.

**Comment by cfdolan** [comment]
What are the first two lists? Are those for alerts or for permission to perform those operations?

**Comment by tressahelvey** [comment]
Hi. These are permissions to perform the operations. Is that something you manage? Thank you.

**Comment by cfdolan** [comment]
Those users have the permissions as recognized Members of the group so all three items are complete. I've added Andriy to the alert email list.

**Comment by tressahelvey** [comment]
Thank you...


______________________________
Regards,
Tressa Helvey-Kasulke
NASA/Goddard Space Flight Center
Project Manager, HDRL
Cell: 202-870-4363

From: cfdolan ***@***.***>
Sent: Wednesday, July 12, 2023 11:57 AM
To: spase-group/SPASE-General ***@***.***>
Cc: Helvey-Kasulke, Tressa L. (GSFC-672.0)[ASRC FEDERAL SYSTEM SOLUTIONS] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [spase-group/SPASE-General] Add a name to Notification (Issue #3)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Those users have the permissions as recognized Members of the group so all three items are complete.

-

**Comment by tressahelvey** [comment]
complete
