### ISSUE TITLE
Git Push Notifications need to be narrowed

### ISSUE THREAD

**Issue by tressahelvey** [spase-group/SPASE-General#6]
Some recent push notifications have included non-xml files, like PDF, .gz, etc.
Jen expects to load all .xml file pushes into EXIST database.
Is there any way to stop non-xml files from getting a push notification?

Additionally, if Lee is testing .xml, is there a way to exclude these test files? As Jen should not include them in the EXIST database.

**Comment by cfdolan** [comment]
I've updated the .gitignore files across the Naming Authority repositories and the new initialization template to ignore all files other than XML, root-folder bookkeeping files, and the workflow yaml files. Only Spase XML files are updated with any regularity so this should cut down on noise significantly. 

These are the blocking instructions:
```
# Restrict commits to Spase XML files and occasional updates to github workflow yml files
# The '!' character negates blocking - use that to allow specific file types

# Ignore all to start
*

# Allow necessary root files
!.gitignore
!README.*
!LICENSE

# Allow folders
!*/

# Allow xml files
!*.xml
!*.XML

# Allow workflow files 
!.github/workflow/*.yml
```

**Comment by tressahelvey** [comment]
Issue resolved
